_mhary_settings_global:
    resource: "@MharySettingsBundle/Resources/config/routing_global.yml"
    prefix: /global

_mhary_settings_personal:
    resource: "@MharySettingsBundle/Resources/config/routing_personal.yml"
    prefix: /personal