services:
    settings_manager:
      alias: mhary.settings.settings_manager

    mhary.settings.settings_manager:
        class: Mhary\SettingsBundle\Manager\SettingsManager
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@mhary.settings.serializer"
            - "%settings_manager.settings%"

    mhary.settings.cached_settings_manager:
        class: Mhary\SettingsBundle\Manager\CachedSettingsManager
        arguments: ["@mhary.settings.settings_manager", ~, ~]

    mhary.settings.serializer_factory:
        class: Mhary\SettingsBundle\Serializer\SerializerFactory

    mhary.settings.serializer:
        class: Mhary\SettingsBundle\Serializer\PhpSerializer
        factory: ['@mhary.settings.serializer_factory', create]
        arguments: ["%settings_manager.serialization%"]

    form.type.settings_management:
        class: Mhary\SettingsBundle\Form\Type\SettingsType
        arguments:
            - "%settings_manager.settings%"
        tags:
            - { name: form.type }

    twig.extension.settings_extension:
        class: Mhary\SettingsBundle\Twig\SettingsExtension
        arguments:
            - "@settings_manager"
        tags:
            - { name: twig.extension }
