sudo: false

language: php

cache:
    directories:
        - $HOME/.composer/cache/files

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm

matrix:
    include:
        - php: 5.6
          env: SYMFONY_VERSION=3.0.*
        - php: 5.6
          env: SYMFONY_VERSION=3.1.*
        - php: 5.6
          env: SYMFONY_VERSION=3.2.*

env:
    - SYMFONY_VERSION=3.3.*

before_install:
  - travis_retry composer self-update

install:
  - composer require symfony/framework-bundle:${SYMFONY_VERSION} --no-update
  - composer require symfony/form:${SYMFONY_VERSION} --no-update
  - composer require symfony/translation:${SYMFONY_VERSION} --no-update
  - composer update

script:
  - vendor/bin/phpunit
